### ISSUE TITLE
Talk about why we are teaching this to them and when we'll go deeper into it

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/js-basics-intro-to-testing-readme#1]
This lesson feels fairly random. Can you add a section that mentions that testing is how professional developers ensure quality. Because of that we want our graduates to be comfortable around tests. For right now we are just focusing on reading tests. As you progress in your career you'll have to learn how to write tests.

**Comment by gj** [comment]
https://github.com/learn-co-curriculum/js-basics-intro-to-testing-readme/commit/67ecf8aa1256f4d46f0d63e7a35b502fe79afd89
